name: Continuous Integration

on:
  push:
    branches:
    - main
    paths:
    - data/**
    - project/**  

jobs:
  tests-feedback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r ./project/requirements.txt 

    - name: Run tests
      run: ./project/tests.sh  # Replace with the actual path to your tests.sh file

    